### ISSUE TITLE
Move cursor 1 to the left when autocompleting

### ISSUE THREAD

**Issue by s1390** [Farow/hexchat-scripts#3]
First of all, thank you so much for all these scripts.

My question is about autocomplete-no-spaces.pl. I've deleted everything in `@keep`, because I didn't want the space you get when autocompleting a nick at all. 

Now is there a way to not get the space, when you hit `tab`? It gets removed after you press a character, but it's visible before that.

Thanks in advance!

**Comment by s1390** [comment]
I've fixed this by doing adding `Xchat::command 'setcursor -1';` in line 29.

Sorry for the notification.

**Comment by Farow** [comment]
Removing the space immediately after hitting tab results in autocomplete not working anymore. Setting the cursor position to -1 seems to be a nice hack though.

**Comment by s1390** [comment]
Yeah, I just noticed this myself, so I'm forced to go back. Thanks though.

Do you think there's even a way to accomplish this at all?

**Comment by Farow** [comment]
It'd be possible to create your own autocomplete functionality that doesn't add a space at the end. There already exists a [script](http://lwsitu.com/xchat/alt_completion.pl) that kinda does that but I don't have any plans on implementing said functionality.

**Comment by s1390** [comment]
Got it. Thanks for the link!
